// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXsxGWSPyESYD-7AJrDe5-R1MJGpVUaVw',
    appId: '1:941229617468:web:03d21a003e93a7ae8eae39',
    messagingSenderId: '941229617468',
    projectId: 'shop-now-92bdc',
    authDomain: 'shop-now-92bdc.firebaseapp.com',
    storageBucket: 'shop-now-92bdc.firebasestorage.app',
    measurementId: 'G-YFBSP614SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlI7aXmMhhLw-GlsNbE0NzEXpC0FHPyww',
    appId: '1:941229617468:android:fec21a9b1359fc2e8eae39',
    messagingSenderId: '941229617468',
    projectId: 'shop-now-92bdc',
    storageBucket: 'shop-now-92bdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSOPCgDtA_0N3q_-ZEY9XU5gh2KyYO_6U',
    appId: '1:941229617468:ios:f512d27b2d40c2888eae39',
    messagingSenderId: '941229617468',
    projectId: 'shop-now-92bdc',
    storageBucket: 'shop-now-92bdc.firebasestorage.app',
    iosBundleId: 'com.example.shopNow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSOPCgDtA_0N3q_-ZEY9XU5gh2KyYO_6U',
    appId: '1:941229617468:ios:f512d27b2d40c2888eae39',
    messagingSenderId: '941229617468',
    projectId: 'shop-now-92bdc',
    storageBucket: 'shop-now-92bdc.firebasestorage.app',
    iosBundleId: 'com.example.shopNow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXsxGWSPyESYD-7AJrDe5-R1MJGpVUaVw',
    appId: '1:941229617468:web:d3f5d88027144b7f8eae39',
    messagingSenderId: '941229617468',
    projectId: 'shop-now-92bdc',
    authDomain: 'shop-now-92bdc.firebaseapp.com',
    storageBucket: 'shop-now-92bdc.firebasestorage.app',
    measurementId: 'G-XX0DT11BSW',
  );
}
